- name: deploy catalogue binary
  get_url:
    url: "{{ catalogue.bin }}"
    xxx:
    xxx:
  notify: restart catalogue service

- name: copy supervisord script for catalogue
  template:
    src:
    dest:
    mode:
  notify: restart supervisor

- meta: flush_handlers

- name: start frontend service
  supervisorctl:
    xxx:
    xxx: 
