version: '3.0'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes:
  cs-ansible:
  jenkins-docker-certs:
  jenkins-data:

services:
  control:
    image: codespaces/ansible-control:3.0.0
    ports:
      - "8000:8000"
    volumes:
      - cs-ansible:/root/workspace
    networks:
      custom:
        ipv4_address: 192.168.61.10
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: control
    restart: always
  frontend:
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
       - "80:8079"
    networks:
      custom:
        ipv4_address: 192.168.61.11
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: frontend
    restart: always
  catalogue:
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
       - "7081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.12
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: catalogue
    restart: always
  carts:
    image: codespaces/ansible-node-ubuntu:18.04
    ports:
      - "8081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.13
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: carts
    restart: always
  carts-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      custom:
        ipv4_address: 192.168.61.15
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on: 
      - docker

  docker:
    image: docker:dind
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      custom:
        ipv4_address: 192.168.61.16
        aliases:
          - docker
    privileged: true
    domainname: codespaces.io
    hostname: docker
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

